name: called_workflow
on: 
  workflow_call:
    inputs: #inputs passed by caller workflow.
      artifact: 
        description: name of artifact 
        required: false # when set to true, fail workflow if input not passed, when set false, execute workflow anyway
        default: dist # default file to look for if input not passed
        type: string  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4 # downloading the artifact from caller workflow to this runner to perform upload of artifact files
        with:
          name: ${{ inputs.artifact }} 
      - name: list downloaded artifacts
        run: ls
      - name: deploy
        run: echo "deploying...!!"


#if reusable workflows are functions then inputs are args passed and outputs are return values