name: sample-node-app
on: 
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
          node_version: [12, 14, 16] #parallel execution on multiple node versions with different OS
          os_version: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os_version}}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node_version: ${{matrix.node_version}}
      - name: install dependencies
        run: npm ci
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test code
        run: npm run test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: build app
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mynode-app
          path: dist
  deploy:
    needs: publish
    uses: ./.github/workflows/called.yml
    with:
      artifact-name: mynode-app
  # print-deploy-job: 
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print outout from reusable workflow
  #       run: echo "${{ needs.deploy.outputs.result }}" #this is how we are accessing the output from reusable workflow, which we stored with name result.
