name: sample-node-app
on: 
  workflow_dispatch:
jobs:
  setup-node:
    strategy:
      matrix:
          node_version: [12, 14, 16] #parallel execution on multiple node versions with different OS
          os_version: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os_version}}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node_version: ${{matrix.node_version}}
      - name: install dependencies
        run: npm ci
  test:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test code
        run: npm run test
      - name: build app
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: test
    uses: ./.github/workflows/called.yml #calling the workflow and passing input with artifact name.
    with:
      artifact: dist-files
  

